console.log("This is a test file.");
console.log("Testing completed and welcome.");
console.log("All tests passed successfully.");
console.log("All tests failed and spoil.");
console.log("This is a production file.");
console.log("This is dev2.");
console.log("test2.");
console.log("This is dev1.");
console.log("test1.");
console.log("test3.");
console.log("This is a test13");
